console.log("_".repeat(80))
console.log(5 + 3)
console.log("_".repeat(80))
console.log(5 + 3)
console.log("_".repeat(80))
console.log(5 + 3)
console.log("_".repeat(80))
console.log(5 + 3)
console.log("_".repeat(80))
